name: Deploy pythonanywhere webapp

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Re-Deploy Pythonanywhere Django API
        uses: samuelitwaru/parking-lot-rl@main
        with:
          host: 'www.pythonanywhere.com'
          username: ${{ secrets.USERNAME }}
          api_token: ${{ secrets.API_TOKEN }}
          domain_name: ${{ secrets.DOMAIN_NAME }}